services:
  - type: web
    name: diagrams-creator
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: OLLAMA_URL
        value: http://localhost:11434
      - key: OLLAMA_MODEL
        value: llama3.2
      - key: LOG_LEVEL
        value: INFO
      - key: AI_TEMPERATURE
        value: 0.7
      - key: MAX_TOKENS
        value: 2000
      - key: AI_TIMEOUT
        value: 30
      - key: DEFAULT_DIAGRAM_TYPE
        value: auto
      - key: DEFAULT_DIAGRAM_STYLE
        value: modern
      - key: ICON_CACHE_SIZE
        value: 1000
      - key: ICON_SEARCH_LIMIT
        value: 50
      - key: CORS_ORIGINS
        value: "*"
      - key: RATE_LIMIT_PER_MINUTE
        value: 60
      - key: MAX_FILE_SIZE
        value: 16777216
      - key: ALLOWED_EXTENSIONS
        value: txt,pdf,docx,doc,md,json
      - key: ENABLED_EXPORT_FORMATS
        value: xml,svg,png,pdf
      - key: PNG_QUALITY
        value: 95
      - key: PDF_DPI
        value: 300
      - key: DEBUG_MODE
        value: false
      - key: VERBOSE_LOGGING
        value: false
      - key: TEST_MODE
        value: false