services:
  - type: web
    name: azure-diagram-generator
    env: node
    plan: starter
    buildCommand: npm ci --ignore-scripts
    startCommand: npm start
    nodeVersion: 20
    envVars:
      - key: NODE_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://azure-diagram-generator.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: azure-diagrams-db
    plan: starter
    databaseName: azure_diagrams
    user: azure_diagrams_user

  - name: azure-diagrams-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
